[functions]
external_node_modules = ["express"]
external_node_modules = ["dotenv"]
external_node_modules = ["socket.io"]
external_node_modules = ["discord.js"]
node_bundler = "esbuild"

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
